language:
- node_js
node_js:
- '6'
env:
  global:
  # postgres test database credentials
  - secure: Ip6wySAiCREiAmferGjfUyRperUcSyVUx2+JsVHO3ziEF1rJ+w8Qi8JVcnHhoBOdKZ+CLBEvBB1fCZ8Bg5zumzgl3NsDUrsrQA9gGYvosRBVyjmz0lrJrExVHqPBfHybsVi+sRyvfzVejXb0bJR0EtRqQgyOId7jjPx3jn8cilIuOr3imba0Rohev+gbcEUUx6OU7IGWp1EOgX8Na0+ZJPAominvO2T/qRkyIasfCnzqQgcgFHBr/mwwYMWv6KRcEi83+9/81kIL1uhfBg91rBDAKHMUHAR/u1ngB1V5YACyGViryJKsFC12oiTVRmUwsnOpVh7lkymOz9Hg2lGDnUQ2KJSYv6skt5KhLCZGcp6neU40dzA6Rx+tLtwR/d69pGYftH2xHfeYK05+m+nOMZ8AQiZCwlIthfYwkeOudEeBFyfA4G/TtTZySF73SocTnLcvJc+5sRiTDjRI1swvMES0w+MatgSAwb0xJcKQo28mZyUZBA3/r24ssWf5MhT4a0RcGkqREfrtVqQEhXE+zi4dlcALjCHoIBPJaQGK0EWL3/KJQ/ar8wN+1VsUypoMw6U5UlsdWj0C5FVv1MbBJgE7XntF2ycVfyTKDZld5qwFD8b0lE6+WSV874dsxuxJgNsO10J3KDj951+w1p+wXHsXPHHQKCh3V5s54uubnP4=
  # redshift test database credentials
  - secure: RR6VwwIzpE1ocCNelLNwv390gpOUV5Ob0fADcVeQdN080A+t/64aTdQQZW71IeCJqYygq6KwL3HurbdK0rq315n4XKB/De6N2OjxIiKX3nHiHNsibe0xPVyXSEXlmxMdOPEJz4fd0vVmcNBndB3QTnqgvrKDdLcp777ldXbX2YKllmGqgr7BCbciwgLjYkUyimoHMIsaObhdgJrXCgDEzH89LJr5BJqPuhuQ75FVx+AYwDFnI8ksP+zIHMtL8QCKyXWLuexK2LcAwFg8Je8w2FTAF6XVs04A3qP7/HS9EDjzexpQYlsgpQNehg9G+5EYUl37LsGnAxchmliGYtoV1tL6tqrnHVlHNMxJf5BQ+Dy/IunqFu++C2fJ1ocIEDkF2BRWoK3IGK9pqEenDC03Q011R7tY0l3Mz/pDPs7cHYxI7vGezVbHC4F+IZ+i7XtszdZ2YA03cUqMC8eyT7snzsg3YVucUgI5GalU4Tjcf3USlvCvU3/PvzAxpHaDWzLHniiuOuvJnzP2xq8YLXpmzb1kLeMwdvV0Nd9F5Xfz85yEFHmuJt2+IkHVk4gAticQQh555GordsJTbe+GvCGqdv2bPMyxshfyNz0po+rGzVp3STSiAHLHEUqpRgr+lTZhd4w9Rfvmxox4zfO7MZTa+ti/+f8VF5oM9buk0upoW5E=

install:
- npm install
script:
- node tests/configure_tests.js setup
- npm test
- node tests/configure_tests.js teardown
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIRAO6WUPBQAGHJ3A
  secret_access_key:
    secure: ZaEnGi/UVcDCufJSrNRqAxGcQK3s2I22utJeY60UQbda/tHuYfoe9xbWLKklOY77n0xwPTZNa80QkauXX6H+ozjvuWzZNaiqzslvMaheA0uEDeH3zLIPJ0Z4cQJvHiU0N8R+PlBxuOVoPhHaI+7ut694BUYu33PQKuLCoqBxitRm4F8Mips+HTyiuAf7dugkkVg2EPGUFq/JUYQ5u/2x9iJfo4dTBWm7y8uI1q+xwWO4fPxqxffj9q8zb+5rD1etHz1AC1wDWfWOJrAaASioM+GDT5x3LE/f4JWb0vKAFzHo+tJE1z7ayqOL3796SfRcxRTWNKS29wV6g4C0PNAhvjZORlmEGuEYr2fQTT6cSj5/7eBV4TUfPFkRZrWTi9pRmLCFDTaSE6lic6PoThCjw4FmT3zPc214+aQCfRaKWJ9xu6nk/OsCZBQAl8Q8AQxZS6lrTq4Ct9k4XRgkPH0Yy7fCKeRxvKXOEUOMxlMbJGTGS4UbEDvmoOcptTEh+bO1G/heEVkYEWKr0DyUDF26v/ibrdeiSQGfXOh2sWtD1KUf03bnWhRqQkOSUbIAgR94KH3Hp53HN0Uylkl2mWKsrzv8HbW+Q8gAbZ+Fc8oYe+0xN+HugAj4c+gHVAfie86h15pE66JGhVtIZ5geafLVhW0pf9vRi6k1qA9OnirNE2c=
  region: us-east-1
  app: Kinesis-Consumer
  env: kinesisConsumer-env2
  bucket_name: elasticbeanstalk-us-east-1-031052761859
  on:
    repo: UrbanCCD-UChicago/plenario-mapper
notifications:
  slack:
    rooms:
      secure: TFyRsj9towye1rfCrqu+s/aBSZQ5N/+NtNvamLQ8aa8QvSA4nAunTgQI8sHTnIXMWSHEJhYtlGwoYfq8agobyX0O7jQw1cwszPmkewYMPnhzD5k4oCucCbZVOcFDtMPC/BRCnBokCxEok0/R7jcLI584cfLB2YIp83Vks1ctcw5rMaYXp7KPjA/WEUX1ml7kv8RRlF0+p2+AShMJeXHHzTOg1vGqIuJrCKl/Uia+3UnAU99eDF1b3UZQL7zO3XSExMa6oujd0uNgEUSBzk0DJa4E7Gk7ipYJUyCqyXc9OFgXRvFbocFgRPXSEus/LuBZA5Z8LjTxb1U1k/zgZvkHETdJpykk4Z91dqIlhlRMds43BYBS7EAuipBZpLZz57Q/7tiBMpXmuVVbxmUuLHqLA+msnkXZ57qY8AwTSO3WsjEARzPhzz5BhqXGDYQZBlsGCeszzc8g30JoHMn10MiWqAqLzYX+Qj3s0QfSIaL6+en9jx98ZfURJ0q9Ku6wNb6YcdLCLvtoDtUl1oe2DhUoQlS+euWgIfdeq1tcpmePXabe0l2wjRgSep6M4H/iFvtPiqTky5ktMaiyDeaR88bixvy/AmAnhvHT51symrSCLhsgdWfvil0vPlbqR5N/IsP2ShlA3AqpTNOgb5iehf488GXnYBuMRuUpCBD90EPMHgY=
